INSERT INTO `brands` (`id`, `name`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'FIAT', NULL, NULL, NULL),
(2, 'RENAULT', NULL, NULL, NULL),
(3, 'PEUGEOT', NULL, NULL, NULL),
(4, 'JEEP', NULL, NULL, NULL),
(5, 'CITROEN', NULL, NULL, NULL),
(6, 'VARIOS', NULL, NULL, NULL),
(7, 'IVECO', NULL, NULL, NULL),
(8, 'FIAT/PEUGEOT', NULL, NULL, NULL),
(9, 'FIAT/RENAULT', NULL, NULL, NULL),
(10, 'PEUGEOT/CITROEN', NULL, NULL, NULL),
(11, 'RENAULT/IVECO', NULL, NULL, NULL),
(12, 'SIN DATO', NULL, NULL, NULL);
