INSERT INTO `tables` (`name`, `value`, `background_color`, `color`, `description`, `enable`) VALUES
('province', '1', NULL, NULL, 'Ciudad Autónoma de Buenos Aires (CABA)', 1),
('province', '2', NULL, NULL, 'Buenos Aires', 1),
('province', '3', NULL, NULL, 'Catamarca', 1),
('province', '4', NULL, NULL, 'Córdoba', 1),
('province', '5', NULL, NULL, 'Corrientes', 1),
('province', '6', NULL, NULL, 'Entre Ríos', 1),
('province', '7', NULL, NULL, 'Jujuy', 1),
('province', '8', NULL, NULL, 'Mendoza', 1),
('province', '9', NULL, NULL, 'La Rioja', 1),
('province', '10', NULL, NULL, 'Salta', 1),
('province', '11', NULL, NULL, 'San Juan', 1),
('province', '12', NULL, NULL, 'San Luis', 1),
('province', '13', NULL, NULL, 'Santa Fe', 1),
('province', '14', NULL, NULL, 'Santiago del Estero', 1),
('province', '15', NULL, NULL, 'Tucumán', 1),
('province', '16', NULL, NULL, 'Chaco', 1),
('province', '17', NULL, NULL, 'Chubut', 1),
('province', '18', NULL, NULL, 'Formosa', 1),
('province', '19', NULL, NULL, 'Misiones', 1),
('province', '20', NULL, NULL, 'Neuquén', 1),
('province', '21', NULL, NULL, 'La Pampa', 1),
('province', '22', NULL, NULL, 'Río Negro', 1),
('province', '23', NULL, NULL, 'Santa Cruz', 1),
('province', '24', NULL, NULL, 'Tierra del Fuego', 1);
