INSERT INTO `providers` (`name`, `email`, `created_at`, `updated_at`) VALUES
('COMPLETAR', '', NULL, NULL),
('PIRERAYEN', 'gon.pineiro@gmail.com', NULL, NULL),
('TARABORELLI', 'gon.pineiro@gmail.com', NULL, NULL),
('R1', 'gon.pineiro@gmail.com', NULL, NULL),
('BALSAMO', '', NULL, NULL),
('CROMOSOL', 'pedidos@cromosol.com', NULL, NULL),
('ARCORE', 'bahia@arcore.com', NULL, NULL),
('GOYANARTE', 'claudiogoya@hotmail.com', NULL, NULL),
('ROMA', 'pedidos@romaautopartes.com.ar', NULL, NULL),
('AUPESA', 'arielhernan.iglesias@mpsa.com,alberto.buituron@mpsa.com', NULL, NULL),
('ETMAN', '', NULL, NULL),
('LYON PEUGEOT', 'pablo.leoni@automobileslyon.com.ar', NULL, NULL),
('Mediterraneo', 'DTORREGIANI@MEDITERRANEO.COM.AR', NULL, NULL),
('REPUESTOS J. L.', '', NULL, NULL),
('DARSUR', '', NULL, NULL),
('FIAT', '', NULL, NULL),
('GENOVA', '', NULL, NULL),
('RENAULT', '', NULL, NULL),
('PEUGEOT', '', NULL, NULL),
('EURO MOTORS', 'chealy@euro-motors.com.ar', NULL, NULL),
('ALLENDE', '', NULL, NULL),
('DEL VISO', '', NULL, NULL),
('ARMORIQUE', '', NULL, NULL),
('EXPOYER', 'ramirezmauroj@hotmail.com', NULL, NULL),
('TAGLE RENAULT', 'enrique.bruno@autocity.com.ar,hernan.diaz@autocity.com.ar', NULL, NULL),
('GRUPO BS.AS', '', NULL, NULL),
('MOTCOR', 'fattinello@motcor.com.ar', NULL, NULL),
('MERCADO LIBRE', '', NULL, NULL),
('AVANT PEUGEOT', 'gustavo.olmedo@autocity.com.ar,miguel.cerda@autocity.com.ar', NULL, NULL),
('CHAPERMAN', '', NULL, NULL),
('NIX (NISSAN CORDOBA)', 'santiago.amuchastegui@autocity.com.ar,agustin.brunelli@autocity.com.ar', NULL, NULL),
('JEEP - TARABORELLI CARS', 'carlos.sosa@taraborellicars.com,maximiliano.midaglia@taraborellicars.com', NULL, NULL),
('SURPIEZAS (CHEVROLET)', 'mariano@surpiezas.com.ar', NULL, NULL),
('DIETRICH VW', 'atomassini@vwdietrich.com', NULL, NULL),
('ROLEN VW', 'santiago.bravo@autocity.com.ar', NULL, NULL),
('WhatsApp', '', NULL, NULL),
('VALLEY (JEEP / CHRYSLER)', 'carlos.olavarria@pirerayen.com', NULL, NULL),
('ZUPPIROLI', '', NULL, NULL),
('LA NUEVA IMAGEN', '', NULL, NULL),
('ALTRI', '', NULL, NULL),
('RODAMET', '', NULL, NULL),
('AUTONAUTICA', '', NULL, NULL),
('SIEPAL', NULL, NULL, NULL),
('ILLINOIS', NULL, NULL, NULL),
('TARANTO', NULL, NULL, NULL),
('GDT', NULL, NULL, NULL),
('AUTO CLIPS', NULL, NULL, NULL),
('PHALES', NULL, NULL, NULL),
('TEODORO BARTH', NULL, NULL, NULL),
('TIPER', NULL, NULL, NULL),
('LA CASA DEL RENAULT', NULL, NULL, NULL),
('Rural Santa Fe', NULL, NULL, NULL),
('TOMASSI', NULL, NULL, NULL),
('PEUGEOT GERARDO', NULL, NULL, NULL),
('CARBURACION ANTONIO', NULL, NULL, NULL),
('DM AUTOPARTES', NULL, NULL, NULL);
